In [3]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [7]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [8]:
np.arange(10,51,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [9]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.random.randn(5,5)

array([[-0.39802126, -0.58805566,  1.5244074 , -1.26182865, -0.97233445],
       [ 0.67013591,  0.01754274,  2.7426893 , -0.64490301, -0.4916993 ],
       [ 0.77486601,  0.75921646, -0.42106756, -0.83583556,  1.62707584],
       [-0.03184029, -0.07627713, -1.71262503,  0.54860206, -1.36748768],
       [-0.10328362, -0.75823313,  1.0057602 , -0.23801628,  1.29771933]])

In [13]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [14]:
np.arange(0, 1.05, 0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

In [20]:
a = np.random.randint(25, size=(1,25)).reshape(5,5)

In [22]:
print(a)

[[13 19  7 20  9]
 [20  2  4  8  4]
 [12  2 23  1  0]
 [ 3 12 16 11 21]
 [ 3  1  2  3  6]]


In [12]:
a.sum()

315

In [13]:
a.mean()

12.6

In [14]:
np.std(a)

6.800000000000001

In [23]:
a.sum(0)

array([51, 36, 52, 43, 40])

In [38]:
b = np.random.randint(0,101,size=(5,5))

In [39]:
np.median(b)

39.0

In [40]:
b.min()

10

In [41]:
print(b)

[[13 14 99 10 94]
 [39 10 43 25 52]
 [29 58 16 98 67]
 [51 86 92 95 15]
 [34 30 16 41 13]]


In [42]:
b.max()

99

In [47]:
c = np.random.randint(1,101,size=(3,4))

In [4]:
d = np.random.randint(1,101, size=(4,3))

In [50]:
print(d)

[[98 64 37]
 [78 35 43]
 [91 30 91]
 [67 66 42]]


In [57]:
 d = d.transpose()

In [60]:
print(c)

[[62 80 95 51]
 [11 44 73 13]
 [35 13 47 56]]


In [58]:
np.add(c,d)

array([[160, 158, 186, 118],
       [ 75,  79, 103,  79],
       [ 72,  56, 138,  98]])

In [61]:
np.multiply(c,d)

array([[6076, 6240, 8645, 3417],
       [ 704, 1540, 2190,  858],
       [1295,  559, 4277, 2352]])

In [5]:
e = d.transpose()

In [64]:
np.matmul(c,e)

array([[24378, 12984, 16521],
       [12024,  5292,  9488],
       [12473,  7801,  8483]])